Villa_WebMVC/Controllers/VillaNumberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection;
using Villa_Utility;
using Villa_WebMVC.Models;
using Villa_WebMVC.Models.Dto;
using Villa_WebMVC.Models.VM;
using Villa_WebMVC.Services;
using Villa_WebMVC.Services.IServices;

namespace Villa_WebMVC.Controllers
{
    public class VillaNumberController : Controller
    {
        //implement IVillaService +AutoMapper+IVillaNumberService
        private readonly IVillaNumberService _villaNumberService;
        private readonly IMapper _mapper;
        private readonly IVillaService _villaService;

        //dependency injection for implementation
        public VillaNumberController(IVillaNumberService villaNumberService, IMapper mapper, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _mapper = mapper;
            _villaService = villaService;
        }

        //action methods

        //VillaNumber View--------------------------------------------
        public async Task<IActionResult> IndexVillaNumber()
        {
            //declare
            List<VillaNumberDTO> list = new();

            var response = await _villaNumberService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        //Create VillaNumber View------------------------------------
        [Authorize(Roles = "admin")]
        //GET View
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM VillaNumberVM = new();
            var response = await _villaService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaNumberVM.VillaList=JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)).Select(i=>new SelectListItem 
                {
                    Text=i.Name,
                    Value=i.Id.ToString(),
                });                
            }
            return View(VillaNumberVM);
        }

        [Authorize(Roles = "admin")]
        //POST DATA
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM  model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber);
                if (response != null && response.IsSuccess)
                {
                    //sweetalert2 notification
                    TempData["success"] = "Villa number created";
					return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    //check the error to display it in asp-validation-summary
                    TempData["error"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0) ?
                        response.ErrorMessage[0] : "Error Encountered";
                }
            }

            //populate the drop down            
            var resp = await _villaService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (resp != null && resp.IsSuccess)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(resp.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                });
            }
			//sweetalert2 notification
			TempData["error"] = "Error Encountered!";
			return View(model); ;            
        }

        //Update VillaNumber View-----------------------------------------------------
        [Authorize(Roles = "admin")]
        //GET (see info)
        public async Task<IActionResult> UpdateVillaNumber(int villaNo)
        {
            //declare the model
            VillaNumberUpdateVM VillaNumberVM = new();
            //get Info of VillaNumber
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo);
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                VillaNumberVM.VillaNumber=_mapper.Map<VillaNumberUpdateDTO>(model);
            }

            //get Info of VillaList
            response = await _villaService.GetAllAsync<APIResponse>();            
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                
                VillaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                });
                return View(VillaNumberVM);
            }


            return NotFound();
        }

        [Authorize(Roles = "admin")]
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber);
                if (response != null && response.IsSuccess)
                {
                    //sweetalert2 notification
                    TempData["success"] = "Villa number updated!";
					return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    //check the error to display it in asp-validation-summary
                    TempData["error"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0) ?
                        response.ErrorMessage[0] : "Error Encountered";
                }
            }

            //populate the drop down            
            var resp = await _villaService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (resp != null && resp.IsSuccess)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(resp.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                });
            }
			//sweetalert2 notification
			TempData["error"] = "Error Encountered!";
			return View(model); ;
        }

        //DELETE VillaNumber View-----------------------------------------------------
        [Authorize(Roles = "admin")]
        //GET (see info)
        public async Task<IActionResult> DeleteVillaNumber(int villaNo)
        {
            //declare the model
            VillaNumberDeleteVM VillaNumberVM = new();
            //get Info of VillaNumber
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo);
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                VillaNumberVM.VillaNumber = model;
            }

            //get Info of VillaList
            response = await _villaService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                });
                return View(VillaNumberVM);
            }


            return NotFound();
        }

        [Authorize(Roles = "admin")]
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNumber.VillaNo);
            //redirect back to Index view
            if (response != null && response.IsSuccess)
            {
                //sweetalert2 notification
                TempData["success"] = "Villa number deleted!";
				return RedirectToAction(nameof(IndexVillaNumber));
            }
            else
            {
                //check the error to display it in asp-validation-summary
                TempData["error"] = (response.ErrorMessage != null && response.ErrorMessage.Count > 0) ?
                    response.ErrorMessage[0] : "Error Encountered";
            }
            return View(model);
        }
    }   
}

Villa_WebMVC/Views/VillaNumber/CreateVillaNumber.cshtml
@model Villa_WebMVC.Models.VM.VillaNumberCreateVM


@* Web Title *@
@{
    ViewBag.Title = "Create Villa Number-";
}

<form asp-action="CreateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa Number</h1>
        <hr />

        <div class="row">
            @* validation check *@
            <div asp-validation-summary="All" class="text-danger"></div>

            @* VillaNo *@
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            @* Special Details *@
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5" /></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>            

            @* VillaID *@
            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>            

            @* Back Button *@
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to the list</a>
            </div>

            @* Create Button *@
            <div class="col-5 ">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>


</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Villa_WebMVC/Views/VillaNumber/DeleteVillaNumber.cshtml
@* import model type  *@
@model Villa_WebMVC.Models.VM.VillaNumberDeleteVM

@* Web Title *@
@{
    ViewBag.Title = "Delete Villa Number-";
}

<form asp-action="DeleteVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa Number</h1>
        <hr />

        <input hidden asp-for="VillaNumber.VillaNo" />
        <div class="row">

            @* VillaNo *@
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
            </div>

            @* Special Details *@
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for ="VillaNumber.SpecialDetails" disabled class="form-control" rows="5" ></textarea>                
            </div>

            @* VillaID *@
            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" disabled class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>                
            </div>

            @* Back Button *@
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to the list</a>
            </div>

            @* Delete Button *@
            <div class="col-5 ">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>
    </div>


</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Villa_WebMVC/Views/VillaNumber/IndexVillaNumber.cshtml
@* import model *@
@model IEnumerable<Villa_WebMVC.Models.Dto.VillaNumberDTO>
<br />

@* Web Title *@
@{
    ViewBag.Title = "Villa List-";
}

<div class="container- p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa Number List</h1>
        </div>
        <div class="col text-end pt-1">
            <a class="btn btn-outline-primary" asp-controller="VillaNumber" asp-action="CreateVillaNumber"><i class="bi bi-table"></i> Create New Villa Number</a>
        </div>
    </div>

    <table id="villaNumberTable" class="table table-striped " style="width:80%" >
        <thead>
            <tr>
                <th>Villa Name</th>
                <th>Villa Number</th>  
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Villa.Name</td>
                    <td>@item.VillaNo</td>
                    <td class="text-center">
                        <a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-journal-x"></i></a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Villa Name</th>
                <th>Villa Number</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>

@* css *@
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css" rel="stylesheet" />

@section scripts {
    <!-- Reference the external JavaScript file -->
    <script src="~/js/DataTableFile.js"></script>
    <!-- Call the initializeDataTable function with the parameter -->
    <script>
        initializeDataTable('#villaNumberTable');
    </script>

}

Villa_WebMVC/Views/VillaNumber/UpdateVillaNumber.cshtml
@model Villa_WebMVC.Models.VM.VillaNumberUpdateVM

@* Web Title *@
@{
    ViewBag.Title = "Update Villa Number-";
}

<form asp-action="UpdateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Villa Number</h1>
        <hr />

        <input hidden asp-for="VillaNumber.VillaNo" />
        <div class="row"> 
            @* validation check *@
            <div asp-validation-summary="All" class="text-danger"></div>

            @* VillaNo *@
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>

            @* Special Details *@
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5" ></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            @* VillaID *@
            <div class="col-2">                
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:15px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>

            @* Back Button *@
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to the list</a>
            </div>

            @* Update Button *@
            <div class="col-5 ">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>

        </div>
    </div>


</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}