Villa_WebMVC/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using Villa_Utility;
using Villa_WebMVC.Models;
using Villa_WebMVC.Models.Dto;
using Villa_WebMVC.Services.IServices;


namespace Villa_WebMVC.Controllers
{
	public class AuthController : Controller
	{
		//------------------implement------------------------------------------
		private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }
        //------------------login----------------------------------------------
        //GET
        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO obj = new();
            return View(obj);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO obj)
        {
            //get response from loginAsync action 
            APIResponse response= await _authService.LoginAsync<APIResponse>(obj);
            if (response != null && response.IsSuccess)
            {
                
                //deserialize the response
                TokenDTO model = JsonConvert.DeserializeObject<TokenDTO>(Convert.ToString(response.Result));

                //Retrieve values from jwt token
                var handler = new JwtSecurityTokenHandler();
                var jwt=handler.ReadJwtToken(model.AccessToken);

                //tell the httpContext that user is logged In
                var identity=new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                //get role and username from User model
                //identity.AddClaim(new Claim(ClaimTypes.Name,model.User.UserName));
                //identity.AddClaim(new Claim(ClaimTypes.Role, model.User.Role));

                //get role and username from token
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u=>u.Type=="unique_name").Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,principal);

                ////retrieve token and store it in the session
                //HttpContext.Session.SetString(SD.AccessToken, model.AccessToken);

                //token provider
                _tokenProvider.SetToken(model);

                return RedirectToAction("Index","Home");
            }
            else
            {
                ModelState.AddModelError("Custom Error",response.ErrorMessage.FirstOrDefault());
                return View(obj);
            }            
        }

        //------------------register-------------------------------------------
        //GET
        [HttpGet]
		public IActionResult Register()
		{
            //populate the roles 
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.Admin,Value=SD.Admin},
                new SelectListItem{Text=SD.Customer,Value=SD.Customer},
            };  
            ViewBag.RoleList = roleList;
			return View();
		}
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Register(RegisterationRequestDTO obj)
		{
            //assign the default role if not chosen
            if (string.IsNullOrEmpty(obj.Role))
            {
                obj.Role = SD.Customer;
            }
			APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);    
            if (result != null && result.IsSuccess) 
            {
                return RedirectToAction("Login");
            }

            //reload the page with the list of roles
            //populate the roles 
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.Admin,Value=SD.Admin},
                new SelectListItem{Text=SD.Customer,Value=SD.Customer},
            };
            ViewBag.RoleList = roleList;

            return View();
		}

        //------------------------Logout---------------------------------------
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            var token = _tokenProvider.GetToken();
            await _authService.LogoutAsync<APIResponse>(token);
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }

		//------------------------Access Denied--------------------------------
		public IActionResult AccessDenied()
		{
			return View();
		}
	}
}

Villa_WebMVC/Controllers/VillaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Villa_Utility;
using Villa_WebMVC.Models;
using Villa_WebMVC.Models.Dto;
using Villa_WebMVC.Services.IServices;

namespace Villa_WebMVC.Controllers
{
    public class VillaController: Controller
    {
        //implement IVillaService +AutoMapper
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        //dependency injection for implementation
        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }

        //action methods
        
        //Villa View--------------------------------------------
        public async Task<IActionResult> IndexVilla()
        {
            //declare
            List<VillaDTO> list = new();

            var response = await _villaService.GetAllAsync<APIResponse>();
            //validation to deserialize
            if (response !=null && response.IsSuccess) 
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        //Create Villa View------------------------------------
        //Authorize
        [Authorize(Roles ="admin")]
        //GET
        public async Task<IActionResult> CreateVilla()
        {            
            return View();
        }

        [Authorize(Roles = "admin")]
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO dto)
        {
            if (ModelState.IsValid)
            {
                //pass dto to create async 
                var response = await _villaService.CreateAsync<APIResponse>(dto);
                //redirect back to Index view
                if (response != null && response.IsSuccess) 
                {
                    //sweetalert2 notification
                    TempData["success"] = "Villa created!";
                    return RedirectToAction(nameof(IndexVilla));
                }

            }
            //return dto with error if it is invalid
            //sweetalert2 notification
            TempData["error"] = "Error Encountered!";
            return View(dto);
        }

        //Update Villa View-----------------------------------------------------
        [Authorize(Roles = "admin")]
        //GET (see info)
        public async Task<IActionResult> UpdateVilla(int villaID)
        {
            //get Info
            var response = await _villaService.GetAsync<APIResponse>(villaID);
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaDTO model =JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<VillaUpdateDTO>(model));
            }
            return NotFound();
        }


        [Authorize(Roles = "admin")]
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO dto)
        {
            if (ModelState.IsValid)
            {
                //pass dto to create async 
                var response = await _villaService.UpdateAsync<APIResponse>(dto);
                TempData["success"] = "Villa updated!";
                //redirect back to Index view
                if (response != null && response.IsSuccess)
                {
                    
                    return RedirectToAction(nameof(IndexVilla));
                }

            }
            //return dto with error if it is invalid
            //sweetalert2 notification
            TempData["error"] = "Error Encountered!";
            return View(dto);
        }

        //DELETE Villa View-----------------------------------------------------
        [Authorize(Roles = "admin")]
        //GET (see info)
        public async Task<IActionResult> DeleteVilla(int villaID)
        {
            //get Info
            var response = await _villaService.GetAsync<APIResponse>(villaID);
            //validation to deserialize
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin")]
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(VillaDTO dto)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(dto.Id);
            //redirect back to Index view
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa deleted!";
                return RedirectToAction(nameof(IndexVilla));
            }
            //return dto with error if it is invalid
            //sweetalert2 notification
            TempData["error"] = "Error Encountered!";
            return View(dto);
        }
    }
}

Villa_WebMVC/Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Villa_WebMVC/Views/Shared/_Layout.cshtml
@using Villa_Utility
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Extensions


<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] KoyFish Villa</title>
    @* bootswatch *@
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Villa_WebMVC.styles.css" asp-append-version="true" />
    @* bootstrap icon *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    @* bootstrap  *@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     @* mouse effect *@
     @* <link rel="stylesheet" href="~/css/mouse/MouseEffectCss.css" /> *@
</head>
<body>
    
    @* sweetalert2 notification *@
    <partial name="_Notification" />
    @* <canvas id="canvas"></canvas> *@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  box-shadow mb-3" style="background-color:#cb997e">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/icon/homesymbol.png" alt="IconHome" /> Koy Villa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                         
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @if (User.IsInRole(SD.Admin))
                                {
                                    <span>Content Management (Admin) </span>
                                }
                                else
                                {
                                    <span>Booking</span>
                                }
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a></li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                    </ul>       
                    <ul class="navbar-nav d-flex justify-content-center align-items-center flex-grow-1">
                        <form class="d-flex" role="search">
                            <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search" style="width: 400px;">
                           @*  <button class="btn btn-outline-secondary" type="submit">Search</button> *@
                        </form>
                    </ul>
                    <ul class="navbar-nav">
                        @* Use IHttpContextAccessor to check token to toggle login and logout *@
                        @* @if (httpAcc.HttpContext.Session.GetString(SD.AccessToken) != null && httpAcc.HttpContext.Session.GetString(SD.AccessToken).ToString().Length > 0) *@
                        @*   Use Identity Authenticated to check  *@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                    @* toggleswitch for background *@
                    <ul class="navbar-nav p-2 border rounded">
                        <div class="form-check form-switch" id="btnSwitch" >
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" />
                             <label class="form-check label" for="flexSwitchCheckDefault">Mode</label>
                        </div>
                    </ul>                    
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* bootstrap *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    @* dataTable *@
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>
    @* sweetalert2 noti *@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    @*toggleSwtich for background and save the state in a cookie *@
    <script>
        // Function to set a cookie with the specified name, value, and expiration date
        function setCookie(name, value, days) {
            var expires = "";
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "") + expires + "; path=/";
        }
        // Function to get the value of a cookie by name
        function getCookie(name) {
            var nameEQ = name + "=";
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i];
                while (cookie.charAt(0) == ' ') {
                    cookie = cookie.substring(1, cookie.length);
                }
                if (cookie.indexOf(nameEQ) == 0) {
                    return cookie.substring(nameEQ.length, cookie.length);
                }
            }
            return null;
        }
        //toggle the background switch
        document.getElementById("btnSwitch").addEventListener('click', () => 
        {
            var currentColor;
            if (document.documentElement.getAttribute('data-bs-theme') == 'dark') {
                // document.documentElement.setAttribute('data-bs-theme', 'light');
                currentColor = 'light';                
            }
            else {
                // document.documentElement.setAttribute('data-bs-theme', 'dark');
                currentColor = 'dark';                
            }            
            setCookie('backgroundTheme', currentColor, 30);
            document.documentElement.setAttribute('data-bs-theme', currentColor);
        })
        
        //get the color for the background theme
        var storedColor = getCookie('backgroundTheme');
        //select the html element
        var htmlElement = document.querySelector('html');
        htmlElement.setAttribute('data-bs-theme', storedColor);
        
    </script>
    @* mouse effect *@
    @* <script src="~/js/mouse/MouseEffect.js"></script>
    <script>
        // Get the canvas element
        const cMouse = document.getElementById('canvas');

        // Apply pointer-events: none to the canvas
        cMouse.style.pointerEvents = 'none';
    </script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Villa_WebMVC/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] != null)
{
	<script type="text/javascript">
		Swal.fire({
			position: "top-end",
			icon: "success",
			title: '@TempData["success"]',
			showConfirmButton: false,
			timer: 3000,
			timerProgressBar:true
		})
	</script>
}

@if (TempData["error"] != null)
{
	<script type="text/javascript">
		Swal.fire({
			position: "top-end",
			icon: "error",
			title: '@TempData["error"]',
			showConfirmButton: false,
			timer: 3000,
			timerProgressBar: true
		})
	</script>
}